version: '3.8'
name: ethtweet

services:
  db:
    image: mysql:8.3
    restart: always
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'eth_tweet'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
        - ./mysql-data/:/var/lib/mysql
    command: --binlog_expire_logs_seconds 3600
    deploy:
      resources:
        limits:
          cpus: '2'


  ethtweet:
    image: chenjia404/ethtweet:latest
    restart: always
    container_name: 'ethtweet'
    depends_on:
      - db

    volumes:
      - ./keyStore:/app/keyStore
      - ./tweet.yaml:/app/tweet.yaml

    ports:
      - '4001:4001/udp'
      - '4001:4001/tcp'
      - '8080:8080'
    sysctls:
      - net.core.somaxconn=10240
      - net.ipv4.tcp_syncookies=0
